// navigationConfig.js
// navigationConfig.js
const navigationConfig = {
	notShowMobileNav: [
		'signup',
		'leader-board',
		'nare-league',
		'results',
		'my-bets',
		'promotions',
		'smart-soft',
		'virtuals',
		'standing',
		'playouts',
		'bet-history',
		'nare-games',
		'responsible-gambling',
		'promo',
		'smart-play',
		'gameplay',
		'fpl',
		'FPL',
		'how-to-play',
		'cookie-policy',
		'privacy-policy',
		'dispute-resolution',
		'anti-money-laundering',
		'terms-and-conditions'
	],
	showDownload: [
		'nare-games',
		'promo',
		'bethistory',
		'terms-and-conditions',
		'gameplay',
		'smart-play',
		'betslip-slip',
		'betslip-nare',
		'betslip-jackpot',
		'nare-league',
		'bet-history',
		'standing',
		'results',
		'jackpot',
		'smart-soft',
		'virtuals',
		'competition',
		'my-bets',
		'profile',
		'promotions',
		'leader-board',
		'responsible-gambling',
		'match',
		'smart-soft',
		'casino',
		'gameplay',
		'fpl',
		'FPL',
		'how-to-play',
		'privacy-policy',
		'cookie-policy',
		'dispute-resolution',
		'anti-money-laundering'
	]
};

export default navigationConfig;
